services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Cru\ExternalLinkList\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  Cru\ExternalLinkList\Service\ProvideExternalLinkListService:
    public: true

  Cru\ExternalLinkList\Service\ProvideParsedLinkListService:
    public: true
