name: Publish TYPO3 Extension

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y zip

      - name: Determine extension key
        run: echo "EXT_KEY=$(grep "'extensionKey'" ext_emconf.php | cut -d "'" -f 4)" >> $GITHUB_ENV

      - name: Create ZIP package
        run: |
          mkdir -p build
          zip -r build/${{ env.EXT_KEY }}.zip . -x "*.git*" "build/*" "tests/*"

      - name: Upload to TYPO3 TER
        run: |
          curl -X POST https://extensions.typo3.org/api/v1/upload \
            -H "Authorization: Bearer ${{ secrets.TER_API_KEY }}" \
            -F "extension=@build/${{ env.EXT_KEY }}.zip"
